### ISSUE TITLE
Issue with the detail pane

### ISSUE THREAD

**Issue by Supergamer1337** [dariolupo/Daze_Theme#13] opened 2023-02-18 11:02 UTC
So, I just started playnite again today, and then I was greeted with this:

![image](https://user-images.githubusercontent.com/46903500/219856814-ecd4913c-b520-425a-9042-04bf1841eded.png)

As you can see, the description is way too small and details is way too big. I think this might be an issue with the theme. Anybody else have this issue?

**Comment by dariolupo** [comment] 2023-02-18 14:15
Can't find a way to reproduce this, it looks fine on my side. 

What resolution are you using? Also, are you using the suggested settings [shown here ](https://github.com/dariolupo/Daze_Theme#optimal-playnite-settings-to-avoid-issues-and-achieve-whats-shown-in-the-screenshots-more-or-less)?

**Comment by Supergamer1337** [comment] 2023-02-18 14:20
I'm running on 1440p, and using the same settings (except for font sizes, since I found them to be a bit too big personally, doesn't change the issue though )...

**Comment by dariolupo** [comment] 2023-02-18 15:07
That's weird, I'm also on 1440p. Are both Playnite and the theme updated to their latest versions?

**Comment by Supergamer1337** [comment] 2023-02-18 16:03
Yup, they are. The first thing I checked 😅

**Comment by dariolupo** [comment] 2023-02-18 16:11
Ok thank you. Will check this and try to fix it.

**Comment by dariolupo** [comment] 2023-02-20 11:22
Fixed in 2.1.2

**Closed as completed by dariolupo** 2023-02-20 11:22 UTC
Labels: bug

**Comment by nikolay-borzov** [comment] 2026-04-24 18:55
Facing the same issue on 2560x1440

<img width="1284" height="700" alt="Image" src="https://github.com/user-attachments/assets/f58ab19e-54a9-4d56-a14b-ed01079abd59" />
<img width="1284" height="700" alt="Image" src="https://github.com/user-attachments/assets/dd09d10e-4d2d-4064-bfea-35aaba83898a" />

I assume it's caused by wide content in the first column (Details)

Daze: 2.2
Playnite: 10.52
